import { DashboardData } from './types';

export const mockDashboardData: DashboardData = {
  currentUser: {
    displayName: '김국방',
    email: 'kim.defense@kt.com',
    role: 'AI 데이터 포털 운영자',
    currentDate: '2026.06.28',
    status: 'PoC Running',
  },

  summaryMetrics: {
    datasets: 128,
    aiModels: 24,
    activeProjects: 12,
    exportPending: 5,
    creditShortageProjects: 2,
    krmfProgress: 68,
    openSearchAssets: 10,
    openMetadataStatus: '정상',
  },

  notices: [
    {
      id: 'ntc-001',
      title: 'K-Defense AI Data Portal PoC 2차 오픈 안내',
      type: '공지',
      date: '2026-06-25',
      severity: 'info',
    },
    {
      id: 'ntc-002',
      title: '6월 정기 보안 패치 적용 예정 (OpenSearch, Keycloak)',
      type: '보안',
      date: '2026-06-24',
      severity: 'warning',
    },
    {
      id: 'ntc-003',
      title: '크레딧 부족 프로젝트 2건 확인 및 충전 요망',
      type: '시스템',
      date: '2026-06-23',
      severity: 'error',
    },
    {
      id: 'ntc-004',
      title: 'K-RMF 증적 제출 마감일이 7일 남았습니다.',
      type: '정책',
      date: '2026-06-22',
      severity: 'warning',
    },
    {
      id: 'ntc-005',
      title: 'OpenMetadata 커뮤니티 미트업 초청',
      type: '이벤트',
      date: '2026-06-20',
      severity: 'info',
    },
  ],

  recentAssets: [
    {
      id: 'asset-001',
      type: 'dataset',
      name: '전장영상 객체인식 데이터셋 v3.2',
      description: '야간·주간 전장 영상에서 탱크, 장갑차 등을 라벨링한 학습 데이터',
      tags: ['전장영상', '객체인식', 'YOLO'],
      owner: '국방AI개발팀',
      registeredAt: '2026-06-27',
    },
    {
      id: 'asset-002',
      type: 'ai_model',
      name: 'K-Drone 분류 모델 (ResNet50)',
      description: '드론 영상 기반 표적 분류를 위한 PyTorch 모델',
      tags: ['드론', '분류', 'ResNet50'],
      owner: '항공정보과',
      registeredAt: '2026-06-26',
    },
    {
      id: 'asset-003',
      type: 'dataset',
      name: '음성명령어 인식 데이터셋',
      description: '군용 음성명령어 12,000건 수집·전처리 데이터',
      tags: ['음성', 'STT', '명령어'],
      owner: '지휘통신연구소',
      registeredAt: '2026-06-25',
    },
    {
      id: 'asset-004',
      type: 'ai_model',
      name: '자연재해 영상 분할 모델 (SegFormer)',
      description: '위성·드론 영상에서 홍수·산사태 영역을 분할하는 모델',
      tags: ['영상분할', '재해', 'SegFormer'],
      owner: '재난대응팀',
      registeredAt: '2026-06-24',
    },
    {
      id: 'asset-005',
      type: 'dataset',
      name: '군용 도면 메타데이터',
      description: '장비 도면 자산의 메타데이터 및 태그 정의',
      tags: ['도면', '메타데이터', 'OpenMetadata'],
      owner: '체계개발사업단',
      registeredAt: '2026-06-23',
    },
  ],

  myProjects: [
    {
      id: 'proj-001',
      name: 'AI 데이터 거버넌스 PoC',
      status: 'running',
      pm: '김국방',
      endDate: '2026-12-31',
      resourceUsage: 72,
    },
    {
      id: 'proj-002',
      name: '전장영상 학습데이터 구축',
      status: 'running',
      pm: '박전투',
      endDate: '2026-09-30',
      resourceUsage: 58,
    },
    {
      id: 'proj-003',
      name: 'K-RMF 증적 자동화 연구',
      status: 'approved',
      pm: '이보안',
      endDate: '2026-11-15',
      resourceUsage: 35,
    },
    {
      id: 'proj-004',
      name: '국방 AI 모델 저장소 마이그레이션',
      status: 'pending_approval',
      pm: '최모델',
      endDate: '2026-10-20',
      resourceUsage: 12,
    },
  ],

  exportPending: [
    {
      id: 'exp-001',
      targetName: '전장영상 객체인식 데이터셋 v3.2',
      targetType: 'dataset',
      requester: '이연구',
      status: 'reviewing',
      requestedAt: '2026-06-27',
    },
    {
      id: 'exp-002',
      targetName: 'K-Drone 분류 모델 (ResNet50)',
      targetType: 'ai_model',
      requester: '박개발',
      status: 'requested',
      requestedAt: '2026-06-26',
    },
    {
      id: 'exp-003',
      targetName: '군용 OCR Docker 이미지',
      targetType: 'docker_image',
      requester: '최엔지니어',
      status: 'reviewing',
      requestedAt: '2026-06-25',
    },
    {
      id: 'exp-004',
      targetName: '비밀 등급 분류 알고리즘',
      targetType: 'algorithm',
      requester: '정분석',
      status: 'need_revision',
      requestedAt: '2026-06-24',
    },
  ],

  creditSummary: {
    totalRemaining: 482500,
    monthlyEstimate: 135000,
    shortageProjects: 2,
    gpuLimitedProjects: 1,
    warnings: [
      {
        id: 'warn-001',
        projectName: '전장영상 학습데이터 구축',
        message: '잔여 크레딧이 7일 이내에 소진될 예정입니다.',
        severity: 'high',
      },
      {
        id: 'warn-002',
        projectName: 'AI 데이터 거버넌스 PoC',
        message: 'GPU 자원 제한으로 추론 속도가 저하될 수 있습니다.',
        severity: 'medium',
      },
    ],
  },

  krmfProgress: {
    totalControls: 120,
    submitted: 98,
    approved: 82,
    weakPoints: 8,
    progressRate: 68,
    highRiskIssues: [
      {
        id: 'risk-001',
        title: '개발서버 접근통제 로그 보관 주기 미흡',
        severity: 'high',
      },
      {
        id: 'risk-002',
        title: '외부 연계 API 호출 암호화 미적용',
        severity: 'critical',
      },
    ],
  },

  systemStatus: [
    { name: 'Backstage', status: '정상' },
    { name: 'Keycloak', status: '정상' },
    { name: 'OpenSearch', status: '정상' },
    { name: 'OpenMetadata', status: '정상' },
    { name: 'Integrated Search', status: '정상' },
    { name: 'Project Workspace', status: '점검' },
    { name: 'Export Approval', status: '정상' },
    { name: 'Credit Manager', status: '정상' },
    { name: 'K-RMF Evidence', status: '정상' },
  ],

  quickLinks: [
    {
      id: 'ql-search',
      title: 'Integrated Search',
      description: '통합 검색',
      type: 'internal',
      target: '/integrated-search',
    },
    {
      id: 'ql-project',
      title: 'Project Workspace',
      description: '프로젝트 워크스페이스',
      type: 'internal',
      target: '/project-workspace',
    },
    {
      id: 'ql-export',
      title: 'Export Approval',
      description: '반출/반입 승인',
      type: 'internal',
      target: '/export-approval',
    },
    {
      id: 'ql-credit',
      title: 'Credit Manager',
      description: '크레딧 관리',
      type: 'internal',
      target: '/credit-manager',
    },
    {
      id: 'ql-krmf',
      title: 'K-RMF Evidence',
      description: 'K-RMF 증적 관리',
      type: 'internal',
      target: '/krmf-evidence',
    },
    {
      id: 'ql-openmetadata',
      title: 'OpenMetadata',
      description: '데이터 카탈로그',
      type: 'external',
      target: 'http://localhost:8585',
    },
    {
      id: 'ql-opensearch',
      title: 'OpenSearch Dashboards',
      description: '검색·시각화',
      type: 'external',
      target: 'http://localhost:5601',
    },
    {
      id: 'ql-keycloak',
      title: 'Keycloak Admin',
      description: '인증/인가 관리',
      type: 'external',
      target: 'http://localhost:8080/admin',
    },
  ],
};
