import {
  ControlItem,
  Evidence,
  RiskIssue,
  ExternalSubmission,
} from './types';

export const mockControlItems: ControlItem[] = [
  {
    id: 'KRMF-AC-01',
    area: 'access_control',
    name: '사용자 계정 권한관리',
    description:
      '역할 기반 최소권한 원칙에 따른 사용자 계정 및 권한 관리 정책 수립 및 운영',
    applied: true,
    owner: '김관리',
    ownerOrg: '정병호보안팀',
    importance: 'high',
    checkStatus: 'compliant',
    evidenceCount: 3,
    issueCount: 0,
    lastCheckedAt: '2025-06-20T10:00:00Z',
    purpose: '불필요한 권한 부여로 인한 내부 정보 유출 방지',
    targetSystems: ['Keycloak', 'Backstage'],
    relatedProjects: ['DIMS 정비이력 분석 프로젝트', '장비 고장예측 모델 개발'],
    implementationStatus: '정책 수립 및 주기적 권한 검토 운영 중',
    relatedExportRequestIds: [],
    auditLog: [
      '2025-06-01 김관리: 통제항목 등록',
      '2025-06-20 김관리: 점검 완료',
    ],
  },
  {
    id: 'KRMF-AC-02',
    area: 'account_management',
    name: '관리자 접근통제',
    description: '관리자 계정에 대한 강화된 인증 및 접근 이력 관리',
    applied: true,
    owner: '한보안',
    ownerOrg: '정병호보안팀',
    importance: 'high',
    checkStatus: 'checking',
    evidenceCount: 2,
    issueCount: 1,
    lastCheckedAt: '2025-06-22T11:00:00Z',
    purpose: '관리자 권한 남용 및 침해사고 예방',
    targetSystems: ['OpenMetadata', 'OpenSearch'],
    relatedProjects: ['해군 센서 시계열 분석'],
    implementationStatus: 'MFA 적용 검토 중, 접근 로그 수집 완료',
    relatedExportRequestIds: [],
    auditLog: [
      '2025-06-10 한보안: 증빙자료 제출',
      '2025-06-22 한보안: 보완 요청',
    ],
  },
  {
    id: 'KRMF-LM-01',
    area: 'log_management',
    name: '로그인 감사로그 관리',
    description: '사용자 로그인/로그아웃 및 권한 사용 이력의 수집과 보관',
    applied: true,
    owner: '이개발',
    ownerOrg: 'AI운영팀',
    importance: 'high',
    checkStatus: 'compliant',
    evidenceCount: 4,
    issueCount: 0,
    lastCheckedAt: '2025-06-18T09:00:00Z',
    purpose: '비인가 접근 및 권한 남용 사실 확인',
    targetSystems: ['Backstage', 'Keycloak'],
    relatedProjects: ['DIMS 정비이력 분석 프로젝트', 'K-RMF 증빙 자동화 PoC'],
    implementationStatus: '감사로그 수집 및 1년 보관 운영',
    relatedExportRequestIds: [],
    auditLog: [
      '2025-06-05 이개발: 로그 수집 설정 증빙 제출',
      '2025-06-18 한보안: 적합 판정',
    ],
  },
  {
    id: 'KRMF-EN-01',
    area: 'encryption',
    name: '데이터 전송구간 암호화',
    description: '시스템 간 데이터 전송 시 TLS 1.2 이상 적용',
    applied: true,
    owner: 'AI운영팀',
    ownerOrg: 'AI운영팀',
    importance: 'high',
    checkStatus: 'compliant',
    evidenceCount: 2,
    issueCount: 0,
    lastCheckedAt: '2025-06-15T13:00:00Z',
    purpose: '전송 중 데이터 탈취 방지',
    targetSystems: ['Backstage', 'OpenSearch', 'OpenMetadata'],
    relatedProjects: ['장비 고장예측 모델 개발'],
    implementationStatus: '모든 외부 통신 TLS 적용 완료',
    relatedExportRequestIds: [],
    auditLog: ['2025-06-15 AI운영팀: TLS 설정 캡처 제출'],
  },
  {
    id: 'KRMF-EN-02',
    area: 'encryption',
    name: '저장 데이터 암호화',
    description: '민감 데이터 저장 시 암호화 적용 및 키 관리',
    applied: true,
    owner: '최외부',
    ownerOrg: '외부수행사',
    importance: 'high',
    checkStatus: 'remediating',
    evidenceCount: 2,
    issueCount: 2,
    lastCheckedAt: '2025-06-24T10:00:00Z',
    purpose: '저장 매체 분실/유출 시 데이터 보호',
    targetSystems: ['OpenSearch', 'MySQL'],
    relatedProjects: ['부품 수요예측 데이터셋 구축'],
    implementationStatus: '일부 DB 컬럼 암호화 적용 중',
    relatedExportRequestIds: [],
    auditLog: [
      '2025-06-20 최외부: 증빙자료 제출',
      '2025-06-24 한보안: 미흡 사항 2건 발견, 보완 요청',
    ],
  },
  {
    id: 'KRMF-NS-01',
    area: 'network_security',
    name: '반출 승인 이력 관리',
    description: '데이터/모델/문서 반출 시 승인 이력의 생성과 보관',
    applied: true,
    owner: '한보안',
    ownerOrg: '정병호보안팀',
    importance: 'high',
    checkStatus: 'checking',
    evidenceCount: 3,
    issueCount: 0,
    lastCheckedAt: '2025-06-25T14:00:00Z',
    purpose: '비인가 반출 방지 및 추적성 확보',
    targetSystems: ['Export Approval'],
    relatedProjects: ['장비 고장예측 모델 개발', '해군 센서 시계열 분석'],
    implementationStatus: 'Export Approval PoC 기반 승인 이력 관리 중',
    relatedExportRequestIds: ['EXP-2025-001', 'EXP-2025-007'],
    auditLog: ['2025-06-25 한보안: 반출 승인 이력 연계 확인'],
  },
  {
    id: 'KRMF-VM-01',
    area: 'vulnerability_management',
    name: '취약점 점검 및 조치관리',
    description: '운영 환경의 정기적 취약점 점검 및 조치 이력 관리',
    applied: true,
    owner: '정PM',
    ownerOrg: 'AI개발센터',
    importance: 'medium',
    checkStatus: 'non_compliant',
    evidenceCount: 1,
    issueCount: 1,
    lastCheckedAt: '2025-06-23T09:00:00Z',
    purpose: '알려진 취약점으로 인한 침해사고 예방',
    targetSystems: ['Docker 이미지', 'Kubernetes'],
    relatedProjects: ['K-RMF 증빙 자동화 PoC'],
    implementationStatus: '분기별 취약점 점검 미실시',
    relatedExportRequestIds: [],
    auditLog: [
      '2025-06-23 정PM: 점검 결과서 제출',
      '2025-06-23 한보안: 미흡 판정',
    ],
  },
  {
    id: 'KRMF-DP-01',
    area: 'data_protection',
    name: '데이터 분류 및 보호',
    description: '데이터 보안등급(공개/내부/비밀) 분류 및 처리 기준 수립',
    applied: true,
    owner: '박분석',
    ownerOrg: '군수정책과',
    importance: 'high',
    checkStatus: 'compliant',
    evidenceCount: 3,
    issueCount: 0,
    lastCheckedAt: '2025-06-19T10:00:00Z',
    purpose: '데이터 유출 시 영향 최소화',
    targetSystems: ['OpenSearch portal-catalog', 'OpenMetadata'],
    relatedProjects: ['DIMS 정비이력 분석 프로젝트'],
    implementationStatus: '보안등급 기준 정의 및 샘플 데이터 적용 완료',
    relatedExportRequestIds: [],
    auditLog: ['2025-06-19 박분석: 데이터 분류 기준 문서 제출'],
  },
  {
    id: 'KRMF-BR-01',
    area: 'backup_recovery',
    name: '백업 및 복구 절차 관리',
    description: '주요 데이터 및 설정에 대한 백업 계획 수립과 복구 시험',
    applied: false,
    owner: 'AI운영팀',
    ownerOrg: 'AI운영팀',
    importance: 'medium',
    checkStatus: 'not_checked',
    evidenceCount: 0,
    issueCount: 0,
    lastCheckedAt: undefined,
    purpose: '데이터 손상/소손 시 복구능력 확보',
    targetSystems: ['MySQL', 'OpenSearch'],
    relatedProjects: ['K-RMF 증빙 자동화 PoC'],
    implementationStatus: '백업 정책 미수립',
    relatedExportRequestIds: [],
    auditLog: ['2025-06-01 AI운영팀: 적용 대상에서 제외 검토 중'],
  },
  {
    id: 'KRMF-CM-01',
    area: 'change_management',
    name: '변경 이력 관리',
    description: '시스템 변경에 대한 요청-승인-이행 이력 관리',
    applied: true,
    owner: '이개발',
    ownerOrg: 'AI개발센터',
    importance: 'medium',
    checkStatus: 'compliant',
    evidenceCount: 2,
    issueCount: 0,
    lastCheckedAt: '2025-06-21T11:00:00Z',
    purpose: '무단 변경으로 인한 보안사고 예방',
    targetSystems: ['GitLab', 'Backstage'],
    relatedProjects: ['장비 고장예측 모델 개발'],
    implementationStatus: 'Git 커밋 및 MR 기반 변경 이력 관리',
    relatedExportRequestIds: [],
    auditLog: ['2025-06-21 이개발: 변경 이력 샘플 제출'],
  },
  {
    id: 'KRMF-SA-01',
    area: 'security_audit',
    name: '보안 이벤트 모니터링',
    description: '보안 이벤트에 대한 실시간 모니터링 및 알림 체계 운영',
    applied: true,
    owner: '한보안',
    ownerOrg: '정병호보안팀',
    importance: 'high',
    checkStatus: 'completed',
    evidenceCount: 5,
    issueCount: 0,
    lastCheckedAt: '2025-06-26T15:00:00Z',
    purpose: '이상 징후 조기 탐지 및 대응',
    targetSystems: ['Backstage', 'Keycloak'],
    relatedProjects: ['DIMS 정비이력 분석 프로젝트', 'K-RMF 증빙 자동화 PoC'],
    implementationStatus: '이벤트 수집 및 알림 정책 운영 중',
    relatedExportRequestIds: [],
    auditLog: ['2025-06-26 한보안: 모니터링 대시보드 캡처 제출'],
  },
];

export const mockEvidenceList: Evidence[] = [
  {
    id: 'EVD-001',
    controlItemId: 'KRMF-AC-01',
    name: '사용자 권한관리 정책서',
    type: 'policy_document',
    submitter: '김관리',
    submittedAt: '2025-06-05T09:00:00Z',
    reviewer: '한보안',
    status: 'approved',
    filename: '사용자_권한관리_정책_v1.0.pdf',
    version: '1.0',
    note: '연 1회 권한 검토 주기 명시',
  },
  {
    id: 'EVD-002',
    controlItemId: 'KRMF-AC-01',
    name: 'Keycloak 역할 설정 캡처',
    type: 'config_capture',
    submitter: '이개발',
    submittedAt: '2025-06-10T10:00:00Z',
    reviewer: '한보안',
    status: 'approved',
    filename: 'keycloak_roles_20250610.png',
    version: '1.0',
    note: 'portal-admin, developer, analyst 역할 확인',
  },
  {
    id: 'EVD-003',
    controlItemId: 'KRMF-AC-02',
    name: '관리자 접근 로그 샘플',
    type: 'log_file',
    submitter: 'AI운영팀',
    submittedAt: '2025-06-12T11:00:00Z',
    reviewer: '한보안',
    status: 'reviewing',
    filename: 'admin_access_log_202506.csv',
    version: '1.0',
    note: 'MFA 적용 전까지 보완 필요',
  },
  {
    id: 'EVD-004',
    controlItemId: 'KRMF-EN-02',
    name: 'DB 암호화 설정 증빙',
    type: 'config_capture',
    submitter: '최외부',
    submittedAt: '2025-06-20T13:00:00Z',
    reviewer: '한보안',
    status: 'revision_requested',
    filename: 'db_encryption_config.yml',
    version: '0.9',
    note: '민감 컬럼 식별이 불완전함',
  },
  {
    id: 'EVD-005',
    controlItemId: 'KRMF-NS-01',
    name: '반출 승인 이력 샘플',
    type: 'approval_history',
    submitter: '한보안',
    submittedAt: '2025-06-25T14:00:00Z',
    reviewer: '김관리',
    status: 'submitted',
    filename: 'export_approval_history_202506.xlsx',
    version: '1.0',
    note: 'EXP-2025-001, EXP-2025-007 연계',
  },
];

export const mockRiskIssues: RiskIssue[] = [
  {
    id: 'ISS-001',
    controlItemId: 'KRMF-AC-02',
    title: 'OpenMetadata 관리자 MFA 미적용',
    severity: 'high',
    foundAt: '2025-06-22T11:00:00Z',
    owner: 'AI운영팀',
    dueDate: '2025-07-15',
    status: 'in_progress',
    actionContent: 'Keycloak OTP 정책 적용 및 관리자 계정 대상 MFA 활성화',
    residualRisk: 'MFA 적용 전까지 접근 로그 모니터링 강화',
  },
  {
    id: 'ISS-002',
    controlItemId: 'KRMF-EN-02',
    title: '민감 컬럼 암호화 누락',
    severity: 'high',
    foundAt: '2025-06-24T10:00:00Z',
    owner: '최외부',
    dueDate: '2025-07-20',
    status: 'in_progress',
    actionContent: 'OpenSearch 인덱스 중 보안등급=비밀 문서의 특정 필드 암호화',
    residualRisk: '암호화 적용 전 해당 인덱스 접근 제한',
  },
  {
    id: 'ISS-003',
    controlItemId: 'KRMF-EN-02',
    title: '암호화 키 관리 절차 미비',
    severity: 'medium',
    foundAt: '2025-06-24T10:30:00Z',
    owner: '최외부',
    dueDate: '2025-07-25',
    status: 'registered',
    actionContent: '키 관리 정책 수립 및 담당자 지정',
    residualRisk: '임시 키 보관 방식 사용 중',
  },
  {
    id: 'ISS-004',
    controlItemId: 'KRMF-VM-01',
    title: 'Docker 이미지 취약점 조치 지연',
    severity: 'critical',
    foundAt: '2025-06-23T09:00:00Z',
    owner: '정PM',
    dueDate: '2025-07-05',
    status: 'reviewing',
    actionContent: '취약점 패치 적용 및 재빌드',
    residualRisk: '패치 전 해당 이미지 배포 중단',
  },
];

export const mockExternalSubmissions: ExternalSubmission[] = [
  {
    id: 'EXT-001',
    vendorName: 'ICTWAY',
    evidenceName: '접근통제 정책서',
    controlItemId: 'KRMF-AC-01',
    submittedAt: '2025-06-08T09:00:00Z',
    status: 'approved',
    reviewer: '한보안',
    reviewResult: '정책 내용 적합',
    revisionRequested: false,
    note: '내부 정책과 일치함',
  },
  {
    id: 'EXT-002',
    vendorName: '데이터 플랫폼 수행사',
    evidenceName: '데이터 마스킹 설계서',
    controlItemId: 'KRMF-DP-01',
    submittedAt: '2025-06-18T10:00:00Z',
    status: 'revision_requested',
    reviewer: '박분석',
    reviewResult: '내부 등급 적용 범위 보완 필요',
    revisionRequested: true,
    note: '비밀등급 필드 목록 추가 요청',
  },
  {
    id: 'EXT-003',
    vendorName: 'AI 플랫폼 수행사',
    evidenceName: '모델 학습 로그 관리 절차',
    controlItemId: 'KRMF-LM-01',
    submittedAt: '2025-06-15T11:00:00Z',
    status: 'reviewing',
    reviewer: '이개발',
    reviewResult: '검토 중',
    revisionRequested: false,
    note: '로그 보관 기간 명시 필요',
  },
  {
    id: 'EXT-004',
    vendorName: '클라우드 인프라 수행사',
    evidenceName: '백업 설정 증빙',
    controlItemId: 'KRMF-BR-01',
    submittedAt: '2025-06-20T12:00:00Z',
    status: 'not_submitted',
    reviewResult: '해당 통제항목 적용 제외 검토 중',
    revisionRequested: false,
    note: '적용 여부 미확정',
  },
  {
    id: 'EXT-005',
    vendorName: '보안컨설팅 수행사',
    evidenceName: '취약점 점검 결과서',
    controlItemId: 'KRMF-VM-01',
    submittedAt: '2025-06-23T09:00:00Z',
    status: 'submitted',
    reviewer: '정PM',
    reviewResult: '취약점 3건 발견',
    revisionRequested: false,
    note: '조치 완료 후 재검토 예정',
  },
];
