import { AdminConsoleData } from './types';

export const mockAdminData: AdminConsoleData = {
  summary: {
    pendingRegistrations: 4,
    pendingApprovals: 2,
    externalUsers: 18,
    activeUsers: 127,
    lockedAccounts: 3,
    permissionGroups: 7,
    loginPolicies: 4,
    recentSecurityEvents: 12,
  },

  registrations: [
    {
      id: 'reg-001',
      name: '박신청',
      organization: '국방AI연구소',
      email: 'park.apply@kt.ai',
      phone: '010-1234-5678',
      userType: '내부',
      reason: 'AI 데이터 분석 업무 수행을 위한 포털 사용',
      identityVerified: true,
      identityStatus: '확인완료',
      status: '본인확인완료',
      appliedAt: '2026-06-28',
      department: 'AI분석팀',
      position: '선임연구원',
      identityMethod: '이메일 + 휴대폰 본인확인',
      identityVerifiedAt: '2026-06-28 10:30',
      identityResult: '성공',
      verifier: 'system',
      businessPurpose: '전장영상 데이터셋 분석 프로젝트 참여',
      requestedRole: 'analyst',
      requestedServices: ['Portal Dashboard', 'Integrated Search', 'Project Workspace'],
      accessStartDate: '2026-07-01',
      accessEndDate: '2026-12-31',
      securityOathSubmitted: true,
      privacyAgreed: true,
      externalSecurityConfirmed: false,
      reviewComment: '',
    },
    {
      id: 'reg-002',
      name: '최외주',
      organization: '수행사A',
      email: 'choi.vendor@example.com',
      phone: '010-2222-3333',
      userType: '수행사',
      reason: '프로젝트 데이터 라벨링 외주 작업',
      identityVerified: false,
      identityStatus: '미확인',
      status: '신청',
      appliedAt: '2026-06-27',
      department: '라벨링팀',
      position: '사원',
      identityMethod: '외부 사용자 신원 확인서 제출',
      identityVerifiedAt: undefined,
      identityResult: '대기',
      verifier: '-',
      businessPurpose: '군용 음성명령어 데이터 라벨링',
      requestedRole: 'external-user',
      requestedServices: ['Project Workspace'],
      accessStartDate: '2026-07-01',
      accessEndDate: '2026-09-30',
      securityOathSubmitted: false,
      privacyAgreed: true,
      externalSecurityConfirmed: false,
      reviewComment: '',
    },
    {
      id: 'reg-003',
      name: '이협력',
      organization: '협력기관B',
      email: 'lee.partner@example.com',
      phone: '010-4444-5555',
      userType: '외부',
      reason: '공동 연구 데이터 조회',
      identityVerified: true,
      identityStatus: '확인완료',
      status: '검토중',
      appliedAt: '2026-06-26',
      department: '연구지원팀',
      position: '연구원',
      identityMethod: '공공기관 제증명',
      identityVerifiedAt: '2026-06-26 14:00',
      identityResult: '성공',
      verifier: '김국방',
      businessPurpose: '국방 AI 모델 성능 비교 공동연구',
      requestedRole: 'analyst',
      requestedServices: ['Portal Dashboard', 'Integrated Search'],
      accessStartDate: '2026-07-01',
      accessEndDate: '2026-12-31',
      securityOathSubmitted: true,
      privacyAgreed: true,
      externalSecurityConfirmed: true,
      reviewComment: '보안서약 확인 필요',
    },
    {
      id: 'reg-004',
      name: '김거절',
      organization: '컨설팅C',
      email: 'kim.reject@example.com',
      phone: '010-6666-7777',
      userType: '외부',
      reason: '임시 자료 열염',
      identityVerified: false,
      identityStatus: '확인실패',
      status: '반려',
      appliedAt: '2026-06-25',
      department: '컨설팅팀',
      position: '과장',
      identityMethod: '이메일 인증',
      identityVerifiedAt: '2026-06-25 09:10',
      identityResult: '실패',
      verifier: 'system',
      businessPurpose: '자료 조회',
      requestedRole: 'external-user',
      requestedServices: ['Integrated Search'],
      accessStartDate: '2026-07-01',
      accessEndDate: '2026-07-31',
      securityOathSubmitted: false,
      privacyAgreed: false,
      externalSecurityConfirmed: false,
      reviewComment: '신청 사유 불분명, 본인확인 실패',
    },
    {
      id: 'reg-005',
      name: '정보완',
      organization: '수행사D',
      email: 'jung.complete@example.com',
      phone: '010-8888-9999',
      userType: '수행사',
      reason: 'K-RMF 증빙 자료 정리 외주',
      identityVerified: true,
      identityStatus: '확인완료',
      status: '보완요청',
      appliedAt: '2026-06-24',
      department: '보안컨설팅팀',
      position: '대리',
      identityMethod: '외부 사용자 신원 확인서',
      identityVerifiedAt: '2026-06-25 11:00',
      identityResult: '성공',
      verifier: '정감사',
      businessPurpose: 'K-RMF 증빙 자료 정리',
      requestedRole: 'external-user',
      requestedServices: ['Project Workspace', 'K-RMF Evidence'],
      accessStartDate: '2026-07-01',
      accessEndDate: '2026-10-31',
      securityOathSubmitted: true,
      privacyAgreed: true,
      externalSecurityConfirmed: true,
      reviewComment: '접속 종료일 명시 및 담당자 확인서 필요',
    },
  ],

  users: [
    {
      id: 'usr-001',
      name: '김국방',
      accountId: 'kim.defense',
      email: 'kim.defense@kt.ai',
      organization: '국방AI운영팀',
      department: '포털운영그룹',
      role: 'portal-admin',
      userGroup: '관리자그룹',
      userType: '내부',
      accountStatus: '활성',
      lastLoginAt: '2026-06-28 09:15',
      accessibleServices: [
        'Portal Dashboard',
        'Integrated Search',
        'Project Workspace',
        'Export Approval',
        'Credit Manager',
        'K-RMF Evidence',
        'Admin Console',
        'OpenMetadata',
        'OpenSearch Dashboards',
      ],
      accessibleMenus: ['전체 메뉴'],
      dataAccessLevel: '비밀',
      projectAccess: '모든 프로젝트',
      canApproveExport: true,
      canManageCredit: true,
      canAuditKrmf: true,
      locked: false,
    },
    {
      id: 'usr-002',
      name: '박프로',
      accountId: 'park.pm',
      email: 'park.pm@kt.ai',
      organization: '체계개발사업단',
      department: '프로젝트관리팀',
      role: 'project-manager',
      userGroup: 'PM그룹',
      userType: '내부',
      accountStatus: '활성',
      lastLoginAt: '2026-06-28 08:40',
      accessibleServices: [
        'Portal Dashboard',
        'Integrated Search',
        'Project Workspace',
        'Export Approval',
        'Credit Manager',
      ],
      accessibleMenus: ['Project Workspace', 'Export Approval', 'Credit Manager'],
      dataAccessLevel: '내부',
      projectAccess: '소속 프로젝트',
      canApproveExport: true,
      canManageCredit: true,
      canAuditKrmf: false,
      locked: false,
    },
    {
      id: 'usr-003',
      name: '이개발',
      accountId: 'lee.dev',
      email: 'lee.dev@kt.ai',
      organization: 'AI플랫폼팀',
      department: '모델개발그룹',
      role: 'developer',
      userGroup: '개발자그룹',
      userType: '내부',
      accountStatus: '활성',
      lastLoginAt: '2026-06-27 18:22',
      accessibleServices: [
        'Portal Dashboard',
        'Integrated Search',
        'Project Workspace',
        'Credit Manager',
      ],
      accessibleMenus: ['Integrated Search', 'Project Workspace', 'Credit Manager'],
      dataAccessLevel: '내부',
      projectAccess: '참여 프로젝트',
      canApproveExport: false,
      canManageCredit: false,
      canAuditKrmf: false,
      locked: false,
    },
    {
      id: 'usr-004',
      name: '최외부',
      accountId: 'choi.ext',
      email: 'choi.ext@example.com',
      organization: '수행사A',
      department: '라벨링팀',
      role: 'external-user',
      userGroup: '외부사용자그룹',
      userType: '수행사',
      accountStatus: '잠금',
      lastLoginAt: '2026-06-20 11:00',
      accessibleServices: ['Project Workspace'],
      accessibleMenus: ['Project Workspace(제한)'],
      dataAccessLevel: '공개',
      projectAccess: '할당된 업무',
      canApproveExport: false,
      canManageCredit: false,
      canAuditKrmf: false,
      locked: true,
    },
    {
      id: 'usr-005',
      name: '정감사',
      accountId: 'jung.audit',
      email: 'jung.audit@kt.ai',
      organization: '보안감사팀',
      department: '보안통제그룹',
      role: 'security-auditor',
      userGroup: '감사그룹',
      userType: '내부',
      accountStatus: '만료예정',
      lastLoginAt: '2026-06-15 14:10',
      accessibleServices: [
        'Portal Dashboard',
        'K-RMF Evidence',
        'Admin Console',
      ],
      accessibleMenus: ['K-RMF Evidence', 'Audit Log', 'Admin Console(조회)'],
      dataAccessLevel: '내부',
      projectAccess: '감사 대상 프로젝트',
      canApproveExport: false,
      canManageCredit: false,
      canAuditKrmf: true,
      locked: false,
    },
  ],

  externalUsers: [
    {
      id: 'ext-001',
      name: '최외주',
      email: 'choi.vendor@example.com',
      organization: '수행사A',
      company: '(주)수행사A',
      accountStatus: '활성',
      accessStart: '2026-01-01',
      accessEnd: '2026-12-31',
      role: 'external-user',
      accessibleServices: ['Project Workspace'],
      lastLoginAt: '2026-06-27 16:00',
      expiryWarning: false,
    },
    {
      id: 'ext-002',
      name: '이협력',
      email: 'lee.partner@example.com',
      organization: '협력기관B',
      company: '협력기관B',
      accountStatus: '활성',
      accessStart: '2026-04-01',
      accessEnd: '2026-09-30',
      role: 'analyst',
      accessibleServices: ['Portal Dashboard', 'Integrated Search'],
      lastLoginAt: '2026-06-26 10:20',
      expiryWarning: true,
    },
    {
      id: 'ext-003',
      name: '김거절',
      email: 'kim.reject@example.com',
      organization: '컨설팅C',
      company: '컨설팅C',
      accountStatus: '비활성',
      accessStart: '2026-06-01',
      accessEnd: '2026-06-30',
      role: 'external-user',
      accessibleServices: ['Integrated Search'],
      lastLoginAt: undefined,
      expiryWarning: false,
    },
    {
      id: 'ext-004',
      name: '정보완',
      email: 'jung.complete@example.com',
      organization: '수행사D',
      company: '수행사D',
      accountStatus: '활성',
      accessStart: '2026-07-01',
      accessEnd: '2026-10-31',
      role: 'external-user',
      accessibleServices: ['Project Workspace', 'K-RMF Evidence'],
      lastLoginAt: undefined,
      expiryWarning: false,
    },
  ],

  statusHistories: [
    {
      id: 'hist-001',
      timestamp: '2026-06-28 09:00',
      actor: '박신청',
      userId: 'reg-001',
      event: '사용자 등록 신청',
      previousStatus: '-',
      newStatus: '신청',
      reason: 'AI 데이터 분석 업무 신청',
      ip: '10.0.1.20',
    },
    {
      id: 'hist-002',
      timestamp: '2026-06-28 10:30',
      actor: 'system',
      userId: 'reg-001',
      event: '본인확인 완료',
      previousStatus: '신청',
      newStatus: '본인확인완료',
      reason: '이메일 + 휴대폰 본인확인 성공',
      ip: '-',
    },
    {
      id: 'hist-003',
      timestamp: '2026-06-28 11:00',
      actor: '김국방',
      userId: 'reg-001',
      event: '검토 시작',
      previousStatus: '본인확인완료',
      newStatus: '검토중',
      reason: '담당자 배정',
      ip: '10.0.1.10',
    },
    {
      id: 'hist-004',
      timestamp: '2026-06-27 09:00',
      actor: '최외주',
      userId: 'reg-002',
      event: '사용자 등록 신청',
      previousStatus: '-',
      newStatus: '신청',
      reason: '외주 라벨링 업무 신청',
      ip: '10.0.1.21',
    },
    {
      id: 'hist-005',
      timestamp: '2026-06-25 09:10',
      actor: 'system',
      userId: 'reg-004',
      event: '본인확인 완료',
      previousStatus: '신청',
      newStatus: '본인확인완료',
      reason: '이메일 인증 시도',
      ip: '-',
    },
    {
      id: 'hist-006',
      timestamp: '2026-06-25 09:15',
      actor: '김국방',
      userId: 'reg-004',
      event: '반려',
      previousStatus: '검토중',
      newStatus: '반려',
      reason: '본인확인 실패 및 사유 불분명',
      ip: '10.0.1.10',
    },
    {
      id: 'hist-007',
      timestamp: '2026-06-20 11:05',
      actor: 'system',
      userId: 'usr-004',
      event: '계정 잠금',
      previousStatus: '활성',
      newStatus: '잠금',
      reason: '로그인 실패 5회 초과',
      ip: '-',
    },
    {
      id: 'hist-008',
      timestamp: '2026-06-15 14:10',
      actor: '정감사',
      userId: 'usr-005',
      event: '접속 기간 변경',
      previousStatus: '2026-12-31',
      newStatus: '2026-09-30',
      reason: '프로젝트 종료 예정',
      ip: '10.0.1.31',
    },
  ],

  roles: [
    {
      id: 'role-001',
      name: 'portal-admin',
      description: '포털 전체 관리자. 사용자/권한/정책/메뉴 관리 가능',
      target: '내부 관리자',
      accessibleMenus: ['전체 메뉴'],
      dataAccessLevel: '전체 등급',
      projectPermission: '모든 프로젝트 관리',
      approvalAuthority: ['반출 승인', '프로젝트 승인', '사용자 승인'],
      userCount: 3,
    },
    {
      id: 'role-002',
      name: 'project-manager',
      description: '프로젝트 생성 및 멤버/리소스 관리',
      target: '프로젝트 책임자',
      accessibleMenus: ['Project Workspace', 'Export Approval', 'Credit Manager'],
      dataAccessLevel: '내부 이하',
      projectPermission: '소속 프로젝트 관리',
      approvalAuthority: ['반출 승인'],
      userCount: 12,
    },
    {
      id: 'role-003',
      name: 'developer',
      description: 'AI 모델/데이터 개발 및 실험 수행',
      target: '개발자',
      accessibleMenus: ['Integrated Search', 'Project Workspace', 'Credit Manager'],
      dataAccessLevel: '내부 이하(일부 비밀 제한)',
      projectPermission: '참여 프로젝트 조회/수정',
      approvalAuthority: [],
      userCount: 45,
    },
    {
      id: 'role-004',
      name: 'analyst',
      description: '데이터 분석 및 리포트 작성',
      target: '분석가',
      accessibleMenus: ['Integrated Search', 'Project Workspace'],
      dataAccessLevel: '공개/내부',
      projectPermission: '조회 및 분석 작업',
      approvalAuthority: [],
      userCount: 22,
    },
    {
      id: 'role-005',
      name: 'external-user',
      description: '외부/수행사 협력 인력',
      target: '외부 사용자',
      accessibleMenus: ['Project Workspace(제한)'],
      dataAccessLevel: '공개 일부',
      projectPermission: '할당된 업무 조회',
      approvalAuthority: [],
      userCount: 18,
    },
    {
      id: 'role-006',
      name: 'security-auditor',
      description: '보안통제 및 감사 로그 점검',
      target: '보안 감사자',
      accessibleMenus: ['K-RMF Evidence', 'Audit Log', 'Admin Console(조회)'],
      dataAccessLevel: '감사 대상 데이터',
      projectPermission: '감사 대상 프로젝트 조회',
      approvalAuthority: ['K-RMF 증빙 승인'],
      userCount: 5,
    },
    {
      id: 'role-007',
      name: 'data-steward',
      description: '데이터 거버넌스 및 메타데이터 관리',
      target: '데이터 관리자',
      accessibleMenus: ['Integrated Search', 'OpenMetadata'],
      dataAccessLevel: '내부 이하',
      projectPermission: '데이터 자산 등록/품질 관리',
      approvalAuthority: [],
      userCount: 4,
    },
  ],

  loginPolicies: [
    {
      id: 'lp-001',
      name: '내부 사용자 기본 로그인 정책',
      target: '내부 사용자',
      allowedPeriod: '연중무휴 24시간',
      maxFailedAttempts: 5,
      allowDuplicateLogin: false,
      unlockMethod: '관리자 해제 + 본인확인',
      enabled: true,
    },
    {
      id: 'lp-002',
      name: '외부 사용자 제한 로그인 정책',
      target: '외부/수행사 사용자',
      allowedPeriod: '평일 09:00 ~ 18:00',
      maxFailedAttempts: 3,
      allowDuplicateLogin: false,
      unlockMethod: '관리자 해제',
      enabled: true,
    },
    {
      id: 'lp-003',
      name: '관리자 강화 로그인 정책',
      target: 'portal-admin, security-auditor',
      allowedPeriod: '연중무휴 24시간',
      maxFailedAttempts: 3,
      allowDuplicateLogin: false,
      unlockMethod: '보안 담당자 확인 후 해제',
      enabled: true,
    },
    {
      id: 'lp-004',
      name: '수행사 계정 기간 제한 정책',
      target: '수행사 사용자',
      allowedPeriod: '계약 기간 내',
      maxFailedAttempts: 5,
      allowDuplicateLogin: false,
      unlockMethod: '관리자 해제',
      enabled: true,
    },
  ],

  passwordPolicies: [
    {
      id: 'pp-001',
      name: '기본 비밀번호 정책',
      minLength: 8,
      complexity: '영문/숫자/특수문자 1개 이상',
      changeCycleDays: 90,
      expiredLockAction: '즉시 잠금',
      gracePeriodDays: 0,
      reuseLimit: 4,
      target: '전체 사용자',
    },
    {
      id: 'pp-002',
      name: '관리자 강화 비밀번호 정책',
      minLength: 12,
      complexity: '영문 대소문자/숫자/특수문자 2개 이상',
      changeCycleDays: 60,
      expiredLockAction: '즉시 잠금',
      gracePeriodDays: 0,
      reuseLimit: 6,
      target: 'portal-admin, security-auditor',
    },
    {
      id: 'pp-003',
      name: '외부 사용자 유예 정책',
      minLength: 10,
      complexity: '영문/숫자/특수문자 1개 이상',
      changeCycleDays: 90,
      expiredLockAction: '유예기간 후 잠금',
      gracePeriodDays: 7,
      reuseLimit: 4,
      target: '외부/수행사 사용자',
    },
  ],

  auditLogs: [
    {
      id: 'log-001',
      timestamp: '2026-06-28 09:15:32',
      user: 'admin01',
      eventType: '로그인',
      target: 'Backstage',
      ip: '10.0.1.12',
      result: '성공',
      riskLevel: '낮음',
      detail: 'Keycloak OIDC 로그인 성공',
    },
    {
      id: 'log-002',
      timestamp: '2026-06-28 09:12:05',
      user: 'lee.dev',
      eventType: '로그인 실패',
      target: 'Backstage',
      ip: '10.0.1.45',
      result: '실패',
      riskLevel: '보통',
      detail: '비밀번호 3회 실패',
    },
    {
      id: 'log-003',
      timestamp: '2026-06-28 08:55:18',
      user: 'park.pm',
      eventType: '반출 승인',
      target: '전장영상 데이터셋 v3.2',
      ip: '10.0.1.23',
      result: '성공',
      riskLevel: '보통',
      detail: '반출 신청 exp-001 승인',
    },
    {
      id: 'log-004',
      timestamp: '2026-06-27 17:40:22',
      user: 'kim.defense',
      eventType: '관리자 정책 변경',
      target: '내부 사용자 기본 로그인 정책',
      ip: '10.0.1.10',
      result: '성공',
      riskLevel: '높음',
      detail: 'maxFailedAttempts 5 → 3 변경',
    },
    {
      id: 'log-005',
      timestamp: '2026-06-27 16:20:11',
      user: 'jung.audit',
      eventType: '사용자 정보 수정',
      target: 'choi.ext',
      ip: '10.0.1.31',
      result: '성공',
      riskLevel: '보통',
      detail: '계정 상태 잠금으로 변경',
    },
    {
      id: 'log-006',
      timestamp: '2026-06-27 14:10:55',
      user: 'system',
      eventType: '비밀번호 변경',
      target: 'lee.dev',
      ip: '-',
      result: '성공',
      riskLevel: '낮음',
      detail: '정기 변경 주기 도래로 인한 변경',
    },
    {
      id: 'log-007',
      timestamp: '2026-06-27 11:05:40',
      user: 'anonymous',
      eventType: '검색 조회',
      target: 'portal-catalog',
      ip: '10.0.1.99',
      result: '차단',
      riskLevel: '높음',
      detail: '미인증 사용자 검색 시도 차단',
    },
    {
      id: 'log-008',
      timestamp: '2026-06-26 22:30:00',
      user: 'admin01',
      eventType: '로그아웃',
      target: 'Backstage',
      ip: '10.0.1.12',
      result: '성공',
      riskLevel: '낮음',
      detail: '정상 로그아웃',
    },
  ],

  menuItems: [
    {
      id: 'm-001',
      name: '국방지능화플랫폼',
      parent: '-',
      path: '/',
      connectedFeature: 'Portal Dashboard',
      displayOrder: 0,
      enabled: true,
      accessRoles: ['전체'],
      menuType: '메뉴',
    },
    {
      id: 'm-002',
      name: 'Home',
      parent: '국방지능화플랫폼',
      path: '/',
      connectedFeature: 'Portal Dashboard',
      displayOrder: 1,
      enabled: true,
      accessRoles: ['전체'],
      menuType: '메뉴',
    },
    {
      id: 'm-003',
      name: 'Integrated Search',
      parent: '국방지능화플랫폼',
      path: '/integrated-search',
      connectedFeature: 'Integrated Search',
      displayOrder: 2,
      enabled: true,
      accessRoles: ['전체'],
      menuType: '메뉴',
    },
    {
      id: 'm-004',
      name: 'Project Workspace',
      parent: '국방지능화플랫폼',
      path: '/project-workspace',
      connectedFeature: 'Project Workspace',
      displayOrder: 3,
      enabled: true,
      accessRoles: ['portal-admin', 'project-manager', 'developer', 'analyst', 'external-user'],
      menuType: '메뉴',
    },
    {
      id: 'm-005',
      name: 'Export Approval',
      parent: '국방지능화플랫폼',
      path: '/export-approval',
      connectedFeature: 'Export Approval',
      displayOrder: 4,
      enabled: true,
      accessRoles: ['portal-admin', 'project-manager', 'developer'],
      menuType: '메뉴',
    },
    {
      id: 'm-006',
      name: 'Credit Manager',
      parent: '국방지능화플랫폼',
      path: '/credit-manager',
      connectedFeature: 'Credit Manager',
      displayOrder: 5,
      enabled: true,
      accessRoles: ['portal-admin', 'project-manager', 'developer'],
      menuType: '메뉴',
    },
    {
      id: 'm-007',
      name: 'K-RMF Evidence',
      parent: '국방지능화플랫폼',
      path: '/krmf-evidence',
      connectedFeature: 'K-RMF Evidence',
      displayOrder: 6,
      enabled: true,
      accessRoles: ['portal-admin', 'security-auditor', 'project-manager'],
      menuType: '메뉴',
    },
    {
      id: 'm-008',
      name: 'Admin Console',
      parent: '국방지능화플랫폼',
      path: '/admin-console',
      connectedFeature: 'Admin Console',
      displayOrder: 7,
      enabled: true,
      accessRoles: ['portal-admin', 'security-auditor'],
      menuType: '메뉴',
    },
    {
      id: 'm-009',
      name: 'User Management',
      parent: 'Admin Console',
      path: '/admin-console?tab=users',
      connectedFeature: 'User Management',
      displayOrder: 1,
      enabled: true,
      accessRoles: ['portal-admin'],
      menuType: '기능',
    },
    {
      id: 'm-010',
      name: 'Role & Permission',
      parent: 'Admin Console',
      path: '/admin-console?tab=roles',
      connectedFeature: 'Role & Permission',
      displayOrder: 2,
      enabled: true,
      accessRoles: ['portal-admin'],
      menuType: '기능',
    },
    {
      id: 'm-011',
      name: 'Login Policy',
      parent: 'Admin Console',
      path: '/admin-console?tab=login',
      connectedFeature: 'Login Policy',
      displayOrder: 3,
      enabled: true,
      accessRoles: ['portal-admin'],
      menuType: '기능',
    },
    {
      id: 'm-012',
      name: 'Password Policy',
      parent: 'Admin Console',
      path: '/admin-console?tab=password',
      connectedFeature: 'Password Policy',
      displayOrder: 4,
      enabled: true,
      accessRoles: ['portal-admin'],
      menuType: '기능',
    },
    {
      id: 'm-013',
      name: 'Audit Log',
      parent: 'Admin Console',
      path: '/admin-console?tab=audit',
      connectedFeature: 'Audit Log',
      displayOrder: 5,
      enabled: true,
      accessRoles: ['portal-admin', 'security-auditor'],
      menuType: '기능',
    },
    {
      id: 'm-014',
      name: 'Menu Management',
      parent: 'Admin Console',
      path: '/admin-console?tab=menu',
      connectedFeature: 'Menu Management',
      displayOrder: 6,
      enabled: true,
      accessRoles: ['portal-admin'],
      menuType: '기능',
    },
  ],

  requirementCoverage: [
    {
      area: '메인 포털',
      screenImplemented: '완료',
      logicImplemented: '일부',
      coverage: '70%',
      followUp: '실시간 요약 API 연동',
    },
    {
      area: '로그인/로그아웃',
      screenImplemented: '완료',
      logicImplemented: 'Keycloak OIDC 연동',
      coverage: '80%',
      followUp: 'role/group claim 기반 권한 제어',
    },
    {
      area: '사용자 관리',
      screenImplemented: '1차 화면',
      logicImplemented: '미구현',
      coverage: '40%',
      followUp: 'Keycloak/DB 연동 및 상세 화면',
    },
    {
      area: '사용자 등록 승인',
      screenImplemented: '상세 화면',
      logicImplemented: 'mock workflow',
      coverage: '50%',
      followUp: '본인인증 연동 및 승인 workflow',
    },
    {
      area: '외부 사용자 관리',
      screenImplemented: '1차 화면',
      logicImplemented: '미구현',
      coverage: '40%',
      followUp: '계약/기간 연동 및 Keycloak 연동',
    },
    {
      area: '권한 관리',
      screenImplemented: '1차 화면',
      logicImplemented: '미구현',
      coverage: '30%',
      followUp: 'Keycloak role/group 연동',
    },
    {
      area: '로그인 정책 관리',
      screenImplemented: '1차 화면',
      logicImplemented: '미구현',
      coverage: '30%',
      followUp: '정책 엔진 연동',
    },
    {
      area: '비밀번호 정책 관리',
      screenImplemented: '1차 화면',
      logicImplemented: '미구현',
      coverage: '30%',
      followUp: 'Keycloak password policy 연동',
    },
    {
      area: '이력/감사로그 관리',
      screenImplemented: '1차 화면',
      logicImplemented: '미구현',
      coverage: '35%',
      followUp: '중앙 로그 수집 연동',
    },
    {
      area: '메뉴/프로그램 관리',
      screenImplemented: '1차 화면',
      logicImplemented: '미구현',
      coverage: '30%',
      followUp: '동적 메뉴 권한 제어',
    },
    {
      area: '서비스 카탈로그',
      screenImplemented: '미대응',
      logicImplemented: '미구현',
      coverage: '0%',
      followUp: '17단계에서 화면 추가 예정',
    },
    {
      area: '제안 게시판',
      screenImplemented: '미대응',
      logicImplemented: '미구현',
      coverage: '0%',
      followUp: '17단계에서 화면 추가 예정',
    },
    {
      area: '통합검색',
      screenImplemented: '완료',
      logicImplemented: 'OpenSearch 연동',
      coverage: '60%',
      followUp: '권한 필터링, 임베딩 검색',
    },
    {
      area: '반출/반입 관리',
      screenImplemented: '완료',
      logicImplemented: 'mock',
      coverage: '50%',
      followUp: '실제 DB/API 및 파일 저장소 연동',
    },
    {
      area: '프로젝트/워크스페이스 관리',
      screenImplemented: '완료',
      logicImplemented: 'mock',
      coverage: '50%',
      followUp: '실제 DB/API 연동',
    },
    {
      area: '크레딧 관리',
      screenImplemented: '완료',
      logicImplemented: 'mock',
      coverage: '55%',
      followUp: '자원 사용량 연동',
    },
    {
      area: 'K-RMF 증빙관리',
      screenImplemented: '완료',
      logicImplemented: 'mock',
      coverage: '50%',
      followUp: '평가 시스템 연동',
    },
  ],
};
