import { ExportRequest } from './types';

export const mockExportRequests: ExportRequest[] = [
  {
    id: 'EXP-2025-001',
    direction: 'export',
    targetType: 'ai_model',
    targetName: '장비 고장예측 AI 모델',
    targetDescription:
      '육군 장비 정비이력과 센서 데이터를 기반으로 학습한 고장예측 모델. 외부 연구기관 공동 검증용 반출',
    projectId: 'P-2025-002',
    projectName: '장비 고장예측 모델 개발',
    reason: '외부 연구기관과의 모델 성능 검증 및 공동 연구',
    requester: '이개발',
    requesterOrg: 'AI개발센터',
    securityLevel: 'secret',
    visibility: 'restricted',
    accessScope: 'approved_users',
    status: 'approved',
    requestedAt: '2025-06-10T09:00:00Z',
    approver: '한보안',
    approvedAt: '2025-06-12T14:00:00Z',
    downloadable: true,
    attachments: ['모델_반출_검토서.pdf', '공동연구_협약서.pdf'],
    auditLog: [
      { timestamp: '2025-06-10T09:00:00Z', actor: '이개발', action: '신청 등록', result: '완료', note: '초기 신청' },
      { timestamp: '2025-06-11T10:00:00Z', actor: '한보안', action: '보안등급 검토', result: '통과', note: '비밀 등급 적정' },
      { timestamp: '2025-06-12T14:00:00Z', actor: '한보안', action: '승인 완료', result: '승인', note: '다운로드 허용' },
    ],
  },
  {
    id: 'EXP-2025-002',
    direction: 'export',
    targetType: 'algorithm',
    targetName: '부품 수요예측 알고리즘',
    targetDescription:
      '시계열 예측 기반 부품 수요예측 핵심 알고리즘 문서 및 샘플 코드',
    projectId: 'P-2025-002',
    projectName: '장비 고장예측 모델 개발',
    reason: '납품 평가를 위한 알고리즘 설명서 반출',
    requester: '정PM',
    requesterOrg: 'AI개발센터',
    securityLevel: 'internal',
    visibility: 'restricted',
    accessScope: 'approved_users',
    status: 'reviewing',
    requestedAt: '2025-06-15T10:00:00Z',
    downloadable: false,
    attachments: ['알고리즘_설명서_v1.2.pdf'],
    auditLog: [
      { timestamp: '2025-06-15T10:00:00Z', actor: '정PM', action: '신청 등록', result: '완료', note: '' },
      { timestamp: '2025-06-16T09:00:00Z', actor: '한보안', action: '보안등급 검토', result: '검토중', note: '내부 등급 확인 중' },
    ],
  },
  {
    id: 'EXP-2025-003',
    direction: 'export',
    targetType: 'dataset',
    targetName: '육군 장비 정비이력 데이터셋',
    targetDescription:
      '육군 DIMS 정비이력 샘플 데이터. 외부 분석 환경에서의 재현 실험용',
    projectId: 'P-2025-001',
    projectName: 'DIMS 정비이력 분석 프로젝트',
    reason: '외부 분석 환경 재현 실험',
    requester: '박분석',
    requesterOrg: '군수정책과',
    securityLevel: 'internal',
    visibility: 'private',
    accessScope: 'project_members',
    status: 'need_revision',
    requestedAt: '2025-06-18T11:00:00Z',
    downloadable: false,
    attachments: ['데이터셋_반출_신청서.xlsx'],
    revisionNote: '데이터 마스킹 범위와 반출 기간을 명시해주세요.',
    auditLog: [
      { timestamp: '2025-06-18T11:00:00Z', actor: '박분석', action: '신청 등록', result: '완료', note: '' },
      { timestamp: '2025-06-19T13:00:00Z', actor: '한보안', action: '보안등급 검토', result: '보완요청', note: '마스킹 범위 미흡' },
    ],
  },
  {
    id: 'EXP-2025-004',
    direction: 'import',
    targetType: 'document',
    targetName: 'K-RMF 증빙 가이드 문서',
    targetDescription:
      '외부 감사 수행사로부터 수령한 K-RMF 증빙 자료 및 체크리스트',
    projectId: 'P-2025-005',
    projectName: 'K-RMF 증빙 자동화 PoC',
    reason: '외부 감사 자료 포털 등록',
    requester: '김관리',
    requesterOrg: '정병호보안팀',
    securityLevel: 'internal',
    visibility: 'restricted',
    accessScope: 'approved_users',
    status: 'import_completed',
    requestedAt: '2025-06-05T08:00:00Z',
    approver: '한보안',
    approvedAt: '2025-06-06T09:00:00Z',
    downloadable: true,
    attachments: ['KRMF_증빙_가이드.pdf'],
    auditLog: [
      { timestamp: '2025-06-05T08:00:00Z', actor: '김관리', action: '반입 신청', result: '완료', note: '' },
      { timestamp: '2025-06-06T09:00:00Z', actor: '한보안', action: '승인 완료', result: '승인', note: '포털 등록 완료' },
    ],
  },
  {
    id: 'EXP-2025-005',
    direction: 'export',
    targetType: 'docker_image',
    targetName: 'fault-prediction-train',
    targetDescription:
      '장비 고장예측 모델 학습용 Docker 이미지. 외부 학습 클러스터 이관용',
    projectId: 'P-2025-002',
    projectName: '장비 고장예측 모델 개발',
    reason: '외부 GPU 클러스터에서 추가 학습 수행',
    requester: '최엔지니어',
    requesterOrg: 'AI개발센터',
    securityLevel: 'public',
    visibility: 'public',
    accessScope: 'approved_users',
    status: 'export_completed',
    requestedAt: '2025-06-01T07:00:00Z',
    approver: 'AI운영팀',
    approvedAt: '2025-06-02T10:00:00Z',
    downloadable: true,
    attachments: ['Docker_이미지_반출_목록.json'],
    auditLog: [
      { timestamp: '2025-06-01T07:00:00Z', actor: '최엔지니어', action: '신청 등록', result: '완료', note: '' },
      { timestamp: '2025-06-02T10:00:00Z', actor: 'AI운영팀', action: '승인 완료', result: '승인', note: 'Harbor 외부 전송 완료' },
    ],
  },
  {
    id: 'EXP-2025-006',
    direction: 'export',
    targetType: 'pypi_package',
    targetName: 'logistics-feature-engineering',
    targetDescription:
      '군수 물류 데이터 전처리 및 피처 엔지니어링 유틸리티 패키지',
    projectId: 'P-2025-001',
    projectName: 'DIMS 정비이력 분석 프로젝트',
    reason: '외부 수행사 개발 환경에서 패키지 사용 허가 요청',
    requester: '이개발',
    requesterOrg: 'AI개발센터',
    securityLevel: 'public',
    visibility: 'public',
    accessScope: 'all_users',
    status: 'rejected',
    requestedAt: '2025-06-20T13:00:00Z',
    approver: '한보안',
    approvedAt: '2025-06-21T09:00:00Z',
    downloadable: false,
    attachments: ['PyPI_패키지_설명서.md'],
    auditLog: [
      { timestamp: '2025-06-20T13:00:00Z', actor: '이개발', action: '신청 등록', result: '완료', note: '' },
      { timestamp: '2025-06-21T09:00:00Z', actor: '한보안', action: '승인자 검토', result: '반려', note: '외부 공개 정책 위배' },
    ],
  },
  {
    id: 'EXP-2025-007',
    direction: 'export',
    targetType: 'dataset',
    targetName: '해군 장비 센서 시계열 데이터셋',
    targetDescription:
      '함정 엔진룸 온도/진동 센서 데이터. 해군 연구소 공동 분석용',
    projectId: 'P-2025-004',
    projectName: '해군 센서 시계열 분석',
    reason: '해군 연구소 공동 분석 데이터 제공',
    requester: '정PM',
    requesterOrg: 'AI개발센터',
    securityLevel: 'secret',
    visibility: 'private',
    accessScope: 'approved_users',
    status: 'requested',
    requestedAt: '2025-06-22T09:00:00Z',
    downloadable: false,
    attachments: ['해군_데이터셋_반출_신청서.pdf'],
    auditLog: [
      { timestamp: '2025-06-22T09:00:00Z', actor: '정PM', action: '신청 등록', result: '완료', note: '최초 신청' },
    ],
  },
  {
    id: 'EXP-2025-008',
    direction: 'export',
    targetType: 'document',
    targetName: 'AI 모델 배포 운영 가이드',
    targetDescription:
      'AI 모델 버전 관리, 배포 파이프라인, 모니터링 기준을 정의한 내부 문서',
    projectId: 'P-2025-002',
    projectName: '장비 고장예측 모델 개발',
    reason: '외부 운영 이관 담당자 교육 자료',
    requester: 'AI운영팀',
    requesterOrg: 'AI운영팀',
    securityLevel: 'internal',
    visibility: 'restricted',
    accessScope: 'project_members',
    status: 'reviewing',
    requestedAt: '2025-06-23T10:00:00Z',
    downloadable: false,
    attachments: ['MLOps_배포가이드_v2.0.pdf'],
    auditLog: [
      { timestamp: '2025-06-23T10:00:00Z', actor: 'AI운영팀', action: '신청 등록', result: '완료', note: '' },
      { timestamp: '2025-06-24T11:00:00Z', actor: '한보안', action: '보안등급 검토', result: '검토중', note: '내부 등급 확인 중' },
    ],
  },
];
