import { SearchResult } from './types';

export const mockSearchResults: SearchResult[] = [
  {
    id: 'dataset-001',
    type: 'dataset',
    name: '육군 장비 정비이력 데이터셋',
    description:
      '육군 주요 장비의 정비 이력, 고장 코드, 부품 교체 기록을 포함한 정형 데이터셋',
    tags: ['군수', '육군', '정비', '장비'],
    owner: '군수정책과',
    securityLevel: 'internal',
    sourceSystem: 'DAPA-MRO',
    url: 'https://example.com/dataset/001',
    createdAt: '2025-01-15T09:00:00Z',
    updatedAt: '2025-06-10T12:30:00Z',
  },
  {
    id: 'model-001',
    type: 'model',
    name: '장비 고장예측 AI 모델',
    description:
      '정비 이력과 센서 데이터를 기반으로 한 장비 고장 예측 머신러닝 모델',
    tags: ['AI', '고장예측', '군수', '예지보전'],
    owner: 'AI개발센터',
    securityLevel: 'internal',
    sourceSystem: 'AI-Factory',
    url: 'https://example.com/model/001',
    createdAt: '2025-04-01T11:00:00Z',
    updatedAt: '2025-06-18T16:20:00Z',
  },
  {
    id: 'docker-001',
    type: 'docker_image',
    name: 'ai-factory/pytorch-inference:2.1.0',
    description: 'PyTorch 기반 AI 모델 추론용 Docker 이미지',
    tags: ['Docker', 'PyTorch', 'AI', '추론'],
    owner: 'AI운영팀',
    securityLevel: 'internal',
    sourceSystem: 'Harbor',
    url: 'https://example.com/docker/001',
    createdAt: '2025-03-10T10:00:00Z',
    updatedAt: '2025-06-15T14:00:00Z',
  },
  {
    id: 'pypi-001',
    type: 'pypi_package',
    name: 'kt-ai-preprocess',
    description: '군수 데이터 전처리 및 특성 공학 유틸리티 패키지',
    tags: ['PyPI', '전처리', 'Python', '군수'],
    owner: 'AI개발센터',
    securityLevel: 'public',
    sourceSystem: 'Private PyPI',
    url: 'https://example.com/pypi/001',
    createdAt: '2025-02-20T09:00:00Z',
    updatedAt: '2025-05-30T11:00:00Z',
  },
  {
    id: 'doc-001',
    type: 'document',
    name: 'K-RMF 증빙관리 가이드',
    description: 'K-RMF 통제항목별 증빙자료 작성 및 검토 가이드 문서',
    tags: ['K-RMF', '보안', '문서', '증빙'],
    owner: '정병호보안팀',
    securityLevel: 'internal',
    sourceSystem: 'Confluence',
    url: 'https://example.com/doc/001',
    createdAt: '2025-05-01T09:00:00Z',
    updatedAt: '2025-06-20T13:00:00Z',
  },
];
